platform: linux

image_resource:
  type: registry-image
  source:
    repository: dohq/bosh-env
    tag: 6.1.1

params:
  AWS_ACCESS_KEY:
  AWS_SECRET_KEY:
  AWS_REGION:
  BOSH_NON_INTERACTIVE:

inputs:
- name: template
- name: bosh-creds
- name: bosh-state

caches:
- path: stemcells

run:
  path: template/ci/scripts/upload-stemcell.sh
