- type: replace
  path: /vm_types/-
  value:
    name: nano
    cloud_properties:
      instance_type: m1.nano

- type: replace
  path: /vm_types/-
  value:
    name: micro
    cloud_properties:
      instance_type: m1.micro

- type: replace
  path: /vm_types/-
  value:
    name: small
    cloud_properties:
      instance_type: m1.small

- type: replace
  path: /vm_types/-
  value:
    name: medium
    cloud_properties:
      instance_type: m1.medium

# replace default large vm_types
- type: replace
  path: /vm_types/name=large
  value:
    name: large
    cloud_properties:
      instance_type: m1.large

- type: replace
  path: /vm_types/-
  value:
    name: xlarge
    cloud_properties:
      instance_type: m1.xlarge

